@set root=%cd%

cd C:\wamp\bin\php\php5.5.12

php C:\wamp\www\tool\mconfig\config_script_aidan.php	active_drop
php C:\wamp\www\tool\mconfig\config_script_aidan.php	active_instance
php C:\wamp\www\tool\mconfig\config_script_aidan.php	active_remind
php C:\wamp\www\tool\mconfig\config_script_aidan.php	active_reward
php C:\wamp\www\tool\mconfig\config_script_aidan.php	active_service
php C:\wamp\www\tool\mconfig\config_script_aidan.php	active_service_shop
php C:\wamp\www\tool\mconfig\config_script_aidan.php	active_service_type
php C:\wamp\www\tool\mconfig\config_script_aidan.php	activity_list
php C:\wamp\www\tool\mconfig\config_script_aidan.php	arena_reward
php C:\wamp\www\tool\mconfig\config_script_aidan.php	arena_shop
php C:\wamp\www\tool\mconfig\config_script_aidan.php	artifact_attr
php C:\wamp\www\tool\mconfig\config_script_aidan.php	artifact_exp
php C:\wamp\www\tool\mconfig\config_script_aidan.php	bag
php C:\wamp\www\tool\mconfig\config_script_aidan.php	bag_drop
php C:\wamp\www\tool\mconfig\config_script_aidan.php	buff
php C:\wamp\www\tool\mconfig\config_script_aidan.php	button_tips
php C:\wamp\www\tool\mconfig\config_script_aidan.php	buy_power_need
php C:\wamp\www\tool\mconfig\config_script_aidan.php	cell
php C:\wamp\www\tool\mconfig\config_script_aidan.php	charge
php C:\wamp\www\tool\mconfig\config_script_aidan.php	city_boss
php C:\wamp\www\tool\mconfig\config_script_aidan.php	city_officer
php C:\wamp\www\tool\mconfig\config_script_aidan.php	counter
php C:\wamp\www\tool\mconfig\config_script_aidan.php	decompose
php C:\wamp\www\tool\mconfig\config_script_aidan.php	decompose_stren
php C:\wamp\www\tool\mconfig\config_script_aidan.php	drop_modulus
php C:\wamp\www\tool\mconfig\config_script_aidan.php	equips_baptiz_change_jade
php C:\wamp\www\tool\mconfig\config_script_aidan.php	equips_baptize
php C:\wamp\www\tool\mconfig\config_script_aidan.php	equips_baptize_lock
php C:\wamp\www\tool\mconfig\config_script_aidan.php	equips_baptize_qian
php C:\wamp\www\tool\mconfig\config_script_aidan.php	equips
php C:\wamp\www\tool\mconfig\config_script_aidan.php	equips_forge
php C:\wamp\www\tool\mconfig\config_script_aidan.php	equips_plus
php C:\wamp\www\tool\mconfig\config_script_aidan.php	equips_quality
php C:\wamp\www\tool\mconfig\config_script_aidan.php	equips_smelt
php C:\wamp\www\tool\mconfig\config_script_aidan.php	equips_soul
php C:\wamp\www\tool\mconfig\config_script_aidan.php	equips_soul_plus
php C:\wamp\www\tool\mconfig\config_script_aidan.php	equips_stren
php C:\wamp\www\tool\mconfig\config_script_aidan.php	equips_suit
php C:\wamp\www\tool\mconfig\config_script_aidan.php	equips_type
php C:\wamp\www\tool\mconfig\config_script_aidan.php	everyday_sign
php C:\wamp\www\tool\mconfig\config_script_aidan.php	examination
php C:\wamp\www\tool\mconfig\config_script_aidan.php	fighting
php C:\wamp\www\tool\mconfig\config_script_aidan.php	forge_consume
php C:\wamp\www\tool\mconfig\config_script_aidan.php	function
php C:\wamp\www\tool\mconfig\config_script_aidan.php	function_notice
php C:\wamp\www\tool\mconfig\config_script_aidan.php	fusion
php C:\wamp\www\tool\mconfig\config_script_aidan.php	gem_upgrade
php C:\wamp\www\tool\mconfig\config_script_aidan.php	gift_download
php C:\wamp\www\tool\mconfig\config_script_aidan.php	goods
php C:\wamp\www\tool\mconfig\config_script_aidan.php	goods_map
php C:\wamp\www\tool\mconfig\config_script_aidan.php	goods_type
php C:\wamp\www\tool\mconfig\config_script_aidan.php	guild_active
php C:\wamp\www\tool\mconfig\config_script_aidan.php	guild
php C:\wamp\www\tool\mconfig\config_script_aidan.php	guild_donation
php C:\wamp\www\tool\mconfig\config_script_aidan.php	guild_shop
php C:\wamp\www\tool\mconfig\config_script_aidan.php	holidays_active
php C:\wamp\www\tool\mconfig\config_script_aidan.php	hook_scene
php C:\wamp\www\tool\mconfig\config_script_aidan.php	hook_star_reward
php C:\wamp\www\tool\mconfig\config_script_aidan.php	instance
php C:\wamp\www\tool\mconfig\config_script_aidan.php	instance_dragon
php C:\wamp\www\tool\mconfig\config_script_aidan.php	instance_single
php C:\wamp\www\tool\mconfig\config_script_aidan.php	log_type
php C:\wamp\www\tool\mconfig\config_script_aidan.php	loop_notice
php C:\wamp\www\tool\mconfig\config_script_aidan.php	lottery_coin
php C:\wamp\www\tool\mconfig\config_script_aidan.php	lottery
php C:\wamp\www\tool\mconfig\config_script_aidan.php	luck
php C:\wamp\www\tool\mconfig\config_script_aidan.php	mail
php C:\wamp\www\tool\mconfig\config_script_aidan.php	mark
php C:\wamp\www\tool\mconfig\config_script_aidan.php	medal
php C:\wamp\www\tool\mconfig\config_script_aidan.php	monster_attack_reward
php C:\wamp\www\tool\mconfig\config_script_aidan.php	monster
php C:\wamp\www\tool\mconfig\config_script_aidan.php	monster_growth
php C:\wamp\www\tool\mconfig\config_script_aidan.php	mounts
php C:\wamp\www\tool\mconfig\config_script_aidan.php	mystery_shop
php C:\wamp\www\tool\mconfig\config_script_aidan.php	notice
php C:\wamp\www\tool\mconfig\config_script_aidan.php	npc
php C:\wamp\www\tool\mconfig\config_script_aidan.php	package_goods
php C:\wamp\www\tool\mconfig\config_script_aidan.php	player_attr
php C:\wamp\www\tool\mconfig\config_script_aidan.php	player_upgrade
php C:\wamp\www\tool\mconfig\config_script_aidan.php	random_first_name
php C:\wamp\www\tool\mconfig\config_script_aidan.php	random_last_name
php C:\wamp\www\tool\mconfig\config_script_aidan.php	random_monster
php C:\wamp\www\tool\mconfig\config_script_aidan.php	robot_account
php C:\wamp\www\tool\mconfig\config_script_aidan.php	robot
php C:\wamp\www\tool\mconfig\config_script_aidan.php	sale_sort
php C:\wamp\www\tool\mconfig\config_script_aidan.php	scene_activity
php C:\wamp\www\tool\mconfig\config_script_aidan.php	scene
php C:\wamp\www\tool\mconfig\config_script_aidan.php	scene_transport
php C:\wamp\www\tool\mconfig\config_script_aidan.php	sensitive_word
php C:\wamp\www\tool\mconfig\config_script_aidan.php	shop
php C:\wamp\www\tool\mconfig\config_script_aidan.php	skill
php C:\wamp\www\tool\mconfig\config_script_aidan.php	skill_tree
php C:\wamp\www\tool\mconfig\config_script_aidan.php	special_drop
php C:\wamp\www\tool\mconfig\config_script_aidan.php	special_drop_type
php C:\wamp\www\tool\mconfig\config_script_aidan.php	stren_rate
php C:\wamp\www\tool\mconfig\config_script_aidan.php	szww_reward
php C:\wamp\www\tool\mconfig\config_script_aidan.php	task_complete
php C:\wamp\www\tool\mconfig\config_script_aidan.php	task
php C:\wamp\www\tool\mconfig\config_script_aidan.php	taskreward
php C:\wamp\www\tool\mconfig\config_script_aidan.php	transfer
php C:\wamp\www\tool\mconfig\config_script_aidan.php	treasure
php C:\wamp\www\tool\mconfig\config_script_aidan.php	ui_function
php C:\wamp\www\tool\mconfig\config_script_aidan.php	vip_boss
php C:\wamp\www\tool\mconfig\config_script_aidan.php	vip
php C:\wamp\www\tool\mconfig\config_script_aidan.php	wander_shop
php C:\wamp\www\tool\mconfig\config_script_aidan.php	wing
php C:\wamp\www\tool\mconfig\config_script_aidan.php	wing_mapping
php C:\wamp\www\tool\mconfig\config_script_aidan.php	world_boss
php C:\wamp\www\tool\mconfig\config_script_aidan.php	world_boss_reward
php C:\wamp\www\tool\mconfig\config_script_aidan.php	worship_goods





pause