<?php

define('SVN_RES_URL', "C:/work/client/wewars/wewars/res");
define('SVN_SRC_URL', "C:/work/client/wewars/wewars/src");


$sourceFileDire = "C:/work2/client/";
$targetFileDire = "C:/work2/tool/package/temp/";
$package_res_Config = array(
	array("25",array(
		array("res/sounds/mp3/","bgm01.mp3"),
		array("res/map/10006/",""),
		array("res/map/10101/",""),
		array("res/map/10102/",""),
		array("res/map/10201/",""),
		array("res/map/10202/",""),
		array("res/map/10301/",""),
		array("res/map/10302/",""),
		array("res/map/10401/",""),
		array("res/map/10402/",""),
		array("res/map/11001/",""),
		array("res/map/20004/",""),
		array("res/map/20005/",""),
		array("res/map/20007/",""),
		array("res/map/20012/",""),
		array("res/map/20013/",""),
		array("res/map/20014/",""),
		array("res/model/1105/",""),
                array("res/model/1106/",""),
                array("res/model/1205/",""),
                array("res/model/1305/",""),
                array("res/model/1306/",""),
                array("res/model/2105/",""),
                array("res/model/2106/",""),
                array("res/model/2205/",""),
                array("res/model/2206/",""),
                array("res/model/2305/",""),
                array("res/model/2306/",""),
                array("res/model/3105/",""),
                array("res/model/3106/",""),
                array("res/model/3107/",""),
                array("res/model/3205/",""),
                array("res/model/3206/",""),
                array("res/model/3207/",""),
                array("res/model/3305/",""),
                array("res/model/3306/",""),
                array("res/model/3307/",""),
                array("res/model/4105/",""),
                array("res/model/4106/",""),
                array("res/model/4107/",""),
                array("res/model/4205/",""),
                array("res/model/4206/",""),
                array("res/model/4207/",""),
                array("res/model/4305/",""),
                array("res/model/4306/",""),
                array("res/model/4307/",""),
                array("res/model/5101/",""),
                array("res/model/5102/",""),
                array("res/model/5103/",""),
                array("res/model/5104/",""),
                array("res/model/5105/",""),
                array("res/model/5106/",""),
                array("res/model/5107/",""),
                array("res/model/5108/",""),
                array("res/model/5109/",""),
                array("res/model/5110/",""),
                array("res/model/6002/",""),
                array("res/model/6003/",""),
                array("res/model/6004/",""),
                array("res/model/6019/",""),
                array("res/model/7530/",""),
                array("res/model/1103/",""),
                array("res/model/1203/",""),
                array("res/model/1303/",""),
                array("res/model/2103/",""),
                array("res/model/2203/",""),
                array("res/model/2303/",""),
                array("res/model/6010/",""),
                array("res/model/6011/",""),
                array("res/model/6012/",""),
                array("res/model/6013/",""),
                array("res/model/6014/",""),
                array("res/model/6017/",""),
                array("res/model/6018/",""),
                array("res/model/6020/",""),
                array("res/model/6021/",""),
                array("res/model/6023/",""),
                array("res/model/6026/",""),
                array("res/model/6027/",""),
                array("res/model/7002/",""),
                array("res/model/7003/",""),
                array("res/model/7004/",""),
                array("res/model/7005/",""),
                array("res/model/7006/",""),
                array("res/model/7010/",""),




	),"package/25.zip",0,"25级资源更新包"),
	
); 

?>